"""empty message

Revision ID: 05e2647f8fa8
Revises: 6a8e85c9a723
Create Date: 2024-10-18 00:50:25.605313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e2647f8fa8'
down_revision = '6a8e85c9a723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('indiancash', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'indiancash')
    # ### end Alembic commands ###
