"""empty message

Revision ID: 8b2c02469542
Revises: bc57a1902231
Create Date: 2024-10-02 00:55:25.796086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2c02469542'
down_revision = 'bc57a1902231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nationality', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'nationality')
    # ### end Alembic commands ###
