"""cash is non null

Revision ID: d0ba1b92a1f2
Revises: 05e2647f8fa8
Create Date: 2024-10-18 10:19:02.699420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ba1b92a1f2'
down_revision = '05e2647f8fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Set default value for existing NULL indiancash values
    op.execute("UPDATE \"user\" SET indiancash = 10000.0 WHERE indiancash IS NULL")
    
    op.alter_column('user', 'cash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('user', 'indiancash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'indiancash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('user', 'cash',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###