"""empty message

Revision ID: e4ae511f0b96
Revises: 86c7ffa690be
Create Date: 2024-10-22 18:53:56.224381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ae511f0b96'
down_revision = '86c7ffa690be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('user', 'hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
